services:
  
  racinglineinator:
    
    build: .
    
    # a name, short for Racinglineinator
    container_name: rl
    
    volumes:
      - ./:/app/src
    
    ports:
      - "5000:5000"
    
    command: python3 app.py
    
    # shared memory size
    shm_size: '2gb'
    
    # this enables the usage of GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]