services:
  racinglineinator:
    build: .
    ports:
      - "5000:5000"
    # a name, short for Racinglineinator
    container_name: rl
    volumes:
      - ./src/:/app/src
      - ./data/:/app/data

    # shared memory size
    shm_size: '2gb'
    
    # this enables the usage of GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]